---
# handlers file for ansible_nagios_graylog2_nsca/

- name: restart graylog-server
  service:
    name: 'graylog-server'
    state: restarted

- name: Reload Nagios
  service:
    name: "{{ nagios_service }}"
    state: reloaded
